apiVersion: certificates:k8s.io/vlbetal
kind: CertificateSigningRequest
metadata:
  name: jane
spec:
  groups:
  - system:authenticated
  usages:
  - digital signature
  - key encipherment
  - server auth
  request:
    #base64 decoded csr file
